### ISSUE TITLE
Standardize dictionary importing

### ISSUE THREAD

**Issue by joshporter1** [joshporter1/codenames#24]
Make it easier for community dictionary contributions. Must support multiple dictionaries for multiple languages (English standard, English CAH, French standard, French CAH, etc...)

Ideas for doing this:

- Standard descriptive naming scheme (ex: en_standard, es_standard, en_cah)
  - Pros: easy to implement, lightweight, drop-in dictionaries
  - Cons: less flexible, possibly confusion and error-prone
- Manifest JSON/YAML file
  - Pros: flexible, extensible, allows for additional metadata
  - Cons: Requires an additional file to be updated for new dictionaries

See additional input and discussion in [this PR](https://github.com/joshporter1/codenames/pull/23).

**Comment by fdenzer** [comment]
Hi,
two-fold question here:

i would go about dictionaries of languages using an i18n-framework in vue, like vuex-i18n or simply vue-i18n.

Second question: if found a word at first glance that made no sense to me. After consulting a wiki I found out it is a very technical word. What are will the procedures for discussion of lists be in your (future) dictionary setup?

(That word is Krümmer, which is not a word most germans actually know [citation needed].
It is found in [Line 171 of german txt](https://github.com/joshporter1/codenames/blob/7e34fa426ea4f66b075f176fd7161b4842d60dbe/server/dictionaries/code_names_german.txt#L171) )

**Comment by joshporter1** [comment]
Using an i18n plugin does seem like a good idea, but would require an overhaul of the dictionary files. I would need help of native speakers to help translate to maintain the same word sets. I am also not sure if the words from the English set correlate one-to-one with German, French, etc, which is why I've relied on others to supply those files for me. 

Using i18n to translate the UI is 100% a great idea. I will open up a separate PR for this since it is unrelated to the dictionary system. 

If you have any other options for more user-friendly dictionary submissions or edits I'm open to suggestions.

**Comment by joshporter1** [comment]
Revisiting this as the number of dictionaries is growing. Plan is to use a dictionaries.yml file to point to each dictionary. File will contain the keys [name, language, path].

@fdenzer - Issue #35 addresses the i18n aspect of the UI. This is 100% on the to-do list once I fix some performance issues and do a bit of refactoring/updating. 

As for the word that made no sense - if there exists a more common word to replace it with feel free to update it. Or notify me and I can do it. I believe the German dictionary was provided by @IBFAIT so they may be able to weigh in here.

**Comment by joshporter1** [comment]
Dictionary info is now stored in dictionaries.yml
