### ISSUE TITLE
Implement hourglass/timer

### ISSUE THREAD

**Issue by IBFAIT** [joshporter1/codenames#31]
Implement hourglass/timer. 

As a player I can start the timer.
As a spymaster I can start the timer.

As a player I get notified when time's up.
As a spymaster I get notified when time's up.

Timer stops when a card is flipped.

**Comment by joshporter1** [comment]
Revisiting this as I roll out some other enhancements and performance fixes. This feature is necessary with so many people playing the game virtually.
