### ISSUE TITLE
Implement i18n for UI elements

### ISSUE THREAD

**Issue by joshporter1** [joshporter1/codenames#35]
The application supports non-English dictionaries but the UI is purely in English. Use vue-i18n to map UI text to supported languages.

**Comment by airon90** [comment]
I just comment to follow the post and to let you know that I can translate the game in Italian and Esperanto ;)

**Comment by joshporter1** [comment]
@airon90 appreciate the offer! We have an Italian dictionary [here](https://github.com/joshporter1/codenames/blob/master/server/dictionaries/default/italian.txt) - feel free to verify that it's correct.

Based on the [English dictionary](https://github.com/joshporter1/codenames/blob/master/server/dictionaries/default/english.txt), you could translate to Esperanto. I can give guidance on adding dictionaries if needed, I plan to create documentation on how to submit dictionaries.

We're still sorting out the i18n side of things, but once that's done, having the UI text translated to Italian and Esperanto would be fantastic!

**Comment by joshporter1** [comment]
PR #60 closes this
