### ISSUE TITLE
Application secret key visible in source code

### ISSUE THREAD

**Issue by dalymople** [joshporter1/codenames#37]
See line 19 in [codenames/server/__init__.py ](https://github.com/joshporter1/codenames/blob/master/server/__init__.py)
Might be a good idea to store this as an environment variable instead and replace with;
~~~~
import os
app.secret_key = os.environ.get('SECRET_KEY')
~~~~

**Comment by joshporter1** [comment]
Secret key moved to env

**Comment by TheCatCameBack-poopyhead** [comment]
What does that mean kitty
