### ISSUE TITLE
Medium links in README are dead

### ISSUE THREAD

**Issue by johannesschweig** [joshporter1/codenames#57]
**Describe the bug**
The medium links you put in the readme redirect to medium.com. 

**To Reproduce**
1. Go to Readme
2. Click any of the links under 'Blog Series'
3. You will be redirected to medium.com

**Expected behavior**
They should link to, for example, https://medium.com/hackervalleystudio/weekend-project-part-3-centralizing-state-management-with-vuex-5f4387ebc144

**Desktop**
 - OS: MacOS 10.15.4
 - Browser: Chrome 81

**Comment by joshporter1** [comment]
Thanks for alerting me of this! I've updated the README with the new links as well as new usage notes.
