### ISSUE TITLE
Clicking on the timer multiple times causes the timer to speed up

### ISSUE THREAD

**Issue by Gonzom** [joshporter1/codenames#59]
**Describe the bug**
Clicking on the timer multiple times causes the timer to speed up like a bomb in a movie.

**To Reproduce**
1. Start a game
2. Click on timer
3. Click "Start Time"
4. Notice seconds pass
5. Click on timer again
6. Click "Start Time" again
7. Notice seconds pass faster
8. Repeat 5-7 over and over again and see how it speeds up
9. Resetting the clock does not fix this

**Expected behavior**
Either an option to click on "Start Time" when the timer is on should not be available, or it should be switched to "Pause Time".

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version:  81.0.4044.129

**Comment by joshporter1** [comment]
Appreciate the bug report - I know exactly what's causing this and will try to fix it by tomorrow. And good call with the pause button!

**Comment by joshporter1** [comment]
Pushed out the fix today. Should toggle between Play and Pause, and if it receives the "start_timer" command twice it will not double up.
